---
- hosts: all
  become: true
  tasks:
  
  - name: Install python3 and pip3
    package:
      name: 
        - python3 
        - python3-pip
      state: latest

  - name: Use pip3 as default pip
    pip:
      name: pip
      executable: pip3

  - name: Install Java in Ubuntu
    apt: 
      name: openjdk-11-jdk
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Create Motd
    copy:
      content: "{{ motd_text | default('Ansible Managed node by SanJose') }}"
      dest: /etc/motd

  - name: Create user
    user:
      name: "{{ 'SanJose' }}"
      state: present
